root_dir: /home/jy/m3vit

db_root_dir: /home/jy/multi_task_datasets
dataset_roots:
  PASCAL_MT: /home/jy/multi_task_datasets/PASCAL_MT
  NYUD_MT: /home/jy/multi_task_datasets/NYUD_MT
  cityscapes: /home/jy/multi_task_datasets/cityscapes

seism_root: /path/to/seism/
