root_dir: ${HOME}/m3vit

db_root_dir: ${HOME}/multi_task_datasets
dataset_roots:
  PASCAL_MT: ${HOME}/multi_task_datasets/PASCAL_MT
  NYUD_MT: ${HOME}/multi_task_datasets/NYUD_MT
  cityscapes: ${HOME}/multi_task_datasets/cityscapes

seism_root: /path/to/seism/
